export const FETCH_USERS = 'FETCH_USERS';

export const FETCH_USER = 'FETCH_USER';

export const FETCH_PHOTO = 'FETCH_PHOTO';

export const FETCH_PHOTOS_BY_KEYWORDS = 'FETCH_PHOTOS_BY_KEYWORDS';

export const FETCH_PHOTOS_BY_USER = 'FETCH_PHOTOS_BY_USER';

export const DELETE_PHOTO = 'DELETE_PHOTO';

export const DELETE_COMMENT = 'DELETE_COMMENT';

export const RESET_PHOTOS = 'RESET_PHOTOS';

export const RESET_PHOTO = 'RESET_PHOTO';

export const POST_PHOTO = 'POST_PHOTO';

export const REGISTER_USER = 'REGISTER_USER';

export const LOGIN_USER = 'LOGIN_USER';

export const UPDATE_SEARCH_KEYWORDS = 'UPDATE_SEARCH_KEYWORDS';

export const UPDATE_SEARCH_CATEGORY = 'UPDATE_SEARCH_TYPE';

export const UPDATE_SEARCH_PAGE = 'UPDATE_SEARCH_PAGE';

export const UPDATE_SEARCH_COUNT = 'UPDATE_SEARCH_COUNT';

export const UPDATE_SEARCH_MESSAGE = 'UPDATE_SEARCH_MESSAGE';

export const UPDATE_PHOTO_COMMENTS = 'UPDATE_PHOTO_COMMENTS';

export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';

export const UPDATE_USER_PROFILE_PICTURE = 'UPDATE_USER_PROFILE_PICTURE';

export const RESET_USERS = 'RESET_USERS';

export const UPDATE_FLASH_MESSAGE = 'UPDATE_ERROR_MESSAGE';

export const RESET_FLASH_MESSAGE = 'RESET_ERROR_MESSAGE';
